version: '3'

volumes:
  data:
  bundle:
  redis:

services:
  db:
    image: postgres:alpine
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  redis:
    image: redis:5.0.5-alpine
    volumes:
      - redis:/data
    ports:
      - 6379:6379
  web:
    build: .
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: postgres://postgres@db
    depends_on:
      - db